spring:
  datasource:
    url: jdbc:mariadb://localhost:53306/member_management_service
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

naver-cloud:
    api:
      access-key: "NAVER_CLOUD_API_ACCESS_KEY"
      secret-key: "NAVER_CLOUD_API_SECRET_KEY"
    sens:
      api:
        service-id: "SENS_API_SERVICE_ID"
        sms:
          message:
            from: "SENS_API_SMS_MESSAGE_FROM"
