spring:
  profiles:
    default: local

naver-cloud:
  api:
    access-key: _
    secret-key: _
  sens:
    api:
      service-id: _
      sms:
        message:
          from: _

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mariadb://localhost:3306/member_management_service
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://member-management-service-mariadb:3306/member_management_service
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
