spring:
  datasource:
    url: jdbc:mariadb://member-management-service-mariadb:53306/member_management_service
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

naver-cloud:
  api:
    access-key: _
    secret-key: _
  sens:
    api:
      service-id: _
      sms:
        message:
          from: _

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
