version: "3.3"
services:

  member-management-service-nginx:
    container_name: member-management-service-nginx
    image: nginx:1.19.6-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./fullchain.pem:/etc/letsencrypt/live/hyeon9mak.o-r.kr/fullchain.pem
      - ./privkey.pem:/etc/letsencrypt/live/hyeon9mak.o-r.kr/privkey.pem    # 직접 옮겨줘야함
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - member-management-service-network

  member-management-service-mariadb:
    container_name: member-management-service-mariadb
    image: mariadb:10.5.18
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: member_management_service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - member-management-service-network

networks:
  member-management-service-network:
    driver: bridge
